import { Project } from "@/types/types.index";

export const projects: Project[] = [
  {
    id: "1",
    title: "Live cron manager",
    description:
      "An automated task scheduler and management dashboard built with Next.js + Typescript + Tailwind for real-time monitoring and control, and node-cron built with Node.js for running recurring backend jobs. The system includes JWT-based authentication, RESTful API communication, and is deployed using Vercel, with MongoDB for handling data storage. This project demonstrates my ability to build and deploy full-stack applications that combine background automation with a user-friendly management interface.",
    image: "/projects/cron-manager/cron-manager.png",
    images: [
      "/projects/cron-manager/project1.png",
      // "/projects/cron-manager/project2.png",
      "/projects/cron-manager/project3.png",
      "/projects/cron-manager/project4.png",
      "/projects/cron-manager/project5.png",
    ],
    technologies: [
      "Next.js",
      "MongoDB",
      "Lucide-react",
      "Bcryptjs",
      "Tailwind",
      "Typescript",
      "Node-mailer",
      "Next-auth",
      "shadcn",
    ],
    githubUrl: "https://github.com/hayzedd-a/cron-manager",
    liveUrl: "https://cron-manager.vercel.app/",
    category: "personal",
    featured: true,
    createdAt: "2025-03-15",
  },
  {
    id: "2",
    title: "Phone Repair web App",
    description:
      "A website for a phone engineer to show their skill and place product for sale",
    image: "/projects/phone-management/phoneManagement1.png",
    images: [
      "/projects/phone-management/phoneManagement1.png",
      "/projects/phone-management/phoneManagement2.png",
      "/projects/phone-management/phoneManagement3.png",
      "/projects/phone-management/phoneManagement4.png",
      "/projects/phone-management/phoneManagement5.png",
    ],
    technologies: ["Next.js", "TypeScript", "Next-auth", "Mongodb", "Tailwind"],
    githubUrl: "https://github.com/Hayzedd-A/tech-engineering",
    liveUrl: "https://tech-engineering-hazel.vercel.app/",
    category: "personal",
    featured: true,
    createdAt: "2025-04-20",
  },
  {
    id: "3",
    title: "My Portfolio",
    description:
      "A portfolio website for a developer to showcase skill, experience, and get to know me better. Features include, light and dark mode, four color scheme, admin section using Next.js authentication, visitor analytics.",
    image: "/projects/portfolio/portfolio1.png",
    images: [
      "/projects/portfolio/portfolio1.png",
      "/projects/portfolio/portfolio2.png",
      "/projects/portfolio/portfolio3.png",
      "/projects/portfolio/portfolio4.png",
    ],
    technologies: [
      "Next.js",
      "TypeScript",
      "MongoDB",
      "framer-motion",
      "GSAP",
      "nodemailer",
      "maxmind/geoip",
    ],
    githubUrl: "https://github.com/Hayzedd-A/hayzedd-the-developer",
    liveUrl: "https://hayzedd-the-developer.vercel.app/contact",
    category: "personal",
    featured: false,
    createdAt: "2025-01-10",
  },
  {
    id: "4",
    title: "Errand Buddies",
    description:
      "An E-Commerce website where vendor can onboard, upload products and make sales on their product. Customers can also onboard, make purchase on products and track their order",
    image: "/projects/errandBuddies/project1.png",
    images: [
      "/projects/errandBuddies/project1.png",
      "/projects/errandBuddies/project2.png",
      "/projects/errandBuddies/project3.png",
      "/projects/errandBuddies/project4.png",
    ],
    technologies: [
      "Express.js",
      "Socket IO",
      "React",
      "YouVerify ID",
      "Cloudinary",
      "Paystack",
      "SMS",
    ],
    liveUrl: "https://errandbuddies.net",
    category: "client",
    featured: true,
    createdAt: "2024-11-10",
  },
  {
    id: "5",
    title: "A store sales management",
    description:
      "A full web app for managing sales in a store or market. Built with react, fetches the product from the an express js server through an API. When each sale is made, the app helps to get the product, record the sale and generate an invoice.",
    image: "/projects/storeKeeper/storeKeeper1.png",
    images: ["/projects/storeKeeper/storeKeeper1.png"],
    technologies: ["Express.js", "React", "SCSS", "AntD", "RestApi", "MySQL"],
    liveUrl: "https://store-keeper-frontend.vercel.app/",
    githubUrl: "https://github.com/Hayzedd-A/storeKeeper-frontend",
    category: "personal",
    featured: false,
    createdAt: "2024-09-05",
  },
  {
    id: "6",
    title: "The google book API",
    description:
      "A dynamic Books Search App built with react that fetches data from the Google Books API and allows users to search for books by title, author, or keyword. By clicking on any book, users are taken to a dedicated single page that provides more detailed information about the book, including its description, publisher, publication date.",
    image: "/projects/googleBooks/project1.png",
    images: [
      "/projects/googleBooks/project1.png",
      "/projects/googleBooks/project2.png",
    ],
    technologies: ["React", "RestAPI", "Google API", "React Router"],
    githubUrl: "https://github.com/Hayzedd-A/Google-bookStore-api",
    liveUrl: "https://google-book-store-api-lime.vercel.app/",
    category: "personal",
    featured: false,
    createdAt: "2024-05-12",
  },
  {
    id: "7",
    title: "A Calender app",
    description:
      "A feature-rich calendar application built with HTML5, CSS3, and jQuery that combines elegant design with powerful functionality. This single-page application dynamically generates accurate calendar layouts through mathematical calculations and provides comprehensive task management capabilities with persistent local storage.",
    image: "/projects/calender/project1.png",
    images: [
      "/projects/calender/project1.png",
      "/projects/calender/project2.png",
      "/projects/calender/project3.png",
    ],
    technologies: ["React Native", "Node.js", "MongoDB", "Express", "Stripe"],
    liveUrl: "https://restaurant-client.com",
    category: "client",
    featured: false,
    createdAt: "2022-06-18",
  },
];
