import { Project } from "@/types/types.index";

export const projects: Project[] = [
  {
    id: "1",
    title: "Live cron manager",
    description:
      "An automated task scheduler and management dashboard built with Next.js + Typescript + Tailwind for real-time monitoring and control, and node-cron built with Node.js for running recurring backend jobs. The system includes JWT-based authentication, RESTful API communication, and is deployed using Vercel, with MongoDB for handling data storage. This project demonstrates my ability to build and deploy full-stack applications that combine background automation with a user-friendly management interface.",
    image: "/projects/cron-manager/cron-manager.png",
    images: [
      "/projects/cron-manager/project1.png",
      // "/projects/cron-manager/project2.png",
      "/projects/cron-manager/project3.png",
      "/projects/cron-manager/project4.png",
      "/projects/cron-manager/project5.png",
    ],
    technologies: [
      "Next.js",
      "MongoDB",
      "Lucide-react",
      "Bcryptjs",
      "Tailwind",
      "Typescript",
      "Node-mailer",
      "Next-auth",
      "shadcn",
    ],
    githubUrl: "https://github.com/hayzedd-a/cron-manager",
    liveUrl: "https://cron-manager.vercel.app/",
    category: "personal",
    featured: true,
    createdAt: "2025-03-15",
  },
  {
    id: "2",
    title: "Phone Repair web App",
    description:
      "A website for a phone engineer to show their skill and place product for sale",
    image: "/projects/phone-management/phoneManagement1.png",
    images: [
      "/projects/phone-management/phoneManagement1.png",
      "/projects/phone-management/phoneManagement2.png",
      "/projects/phone-management/phoneManagement3.png",
      "/projects/phone-management/phoneManagement4.png",
      "/projects/phone-management/phoneManagement5.png",
    ],
    technologies: ["Next.js", "TypeScript", "Next-auth", "Mongodb", "Tailwind"],
    githubUrl: "https://github.com/Hayzedd-A/tech-engineering",
    liveUrl: "https://tech-engineering-hazel.vercel.app/",
    category: "personal",
    featured: true,
    createdAt: "2025-04-20",
  },
  {
    id: "3",
    title: "Weather Dashboard",
    description:
      "Beautiful weather dashboard with location-based forecasts, interactive maps, and detailed weather analytics.",
    image: "/projects/phone-management/phoneManagement1.png",
    images: [
      "/projects/phone-management/phoneManagement1.png",
      "/projects/phone-management/phoneManagement2.png",
      "/projects/phone-management/phoneManagement3.png",
      "/projects/phone-management/phoneManagement4.png",
      "/projects/phone-management/phoneManagement5.png",
    ],
    technologies: ["Vue.js", "TypeScript", "Chart.js", "OpenWeather API"],
    githubUrl: "https://github.com/yourusername/weather",
    liveUrl: "https://your-weather.vercel.app",
    category: "personal",
    featured: false,
    createdAt: "2024-03-10",
  },
  {
    id: "4",
    title: "Corporate Website Redesign",
    description:
      "Complete redesign and development of a corporate website with modern UI/UX, SEO optimization, and CMS integration.",
    image: "/projects/cron-manager.png",
    images: [
      "/projects/netflix.jpg",
      "/projects/newsletter.png",
      "/projects/schoolApp.png",
    ],
    technologies: ["Next.js", "Tailwind CSS", "Strapi", "Vercel"],
    liveUrl: "https://corporate-client.com",
    category: "client",
    featured: true,
    createdAt: "2024-04-05",
  },
  {
    id: "5",
    title: "Social Media Analytics",
    description:
      "Analytics dashboard for social media metrics with real-time data visualization and automated reporting features.",
    image: "/projects/d-dhub.png",
    images: [
      "/projects/netflix.jpg",
      "/projects/newsletter.png",
      "/projects/schoolApp.png",
    ],
    technologies: ["React", "D3.js", "Node.js", "Redis", "PostgreSQL"],
    githubUrl: "https://github.com/yourusername/analytics",
    liveUrl: "https://social-analytics.vercel.app",
    category: "personal",
    featured: false,
    createdAt: "2024-05-12",
  },
  {
    id: "6",
    title: "Restaurant Management System",
    description:
      "Complete restaurant management solution with POS system, inventory management, and customer ordering platform.",
    image: "/projects/esovew.png",
    images: [
      "/projects/netflix.jpg",
      "/projects/newsletter.png",
      "/projects/schoolApp.png",
    ],
    technologies: ["React Native", "Node.js", "MongoDB", "Express", "Stripe"],
    liveUrl: "https://restaurant-client.com",
    category: "client",
    featured: false,
    createdAt: "2024-06-18",
  },
];
